# Security Configuration for Enterprise RAG System

# Authentication
authentication:
  # JWT Configuration
  jwt:
    algorithm: "RS256"  # Use RS256 for production
    public_key_path: "/secrets/jwt_public.pem"
    private_key_path: "/secrets/jwt_private.pem"
    expiration_hours: 24
    refresh_expiration_days: 30
    issuer: "enterprise-rag-system"
    audience: "rag-api"
  
  # OAuth2 Providers
  oauth2:
    providers:
      - name: "okta"
        client_id: ${OKTA_CLIENT_ID}
        client_secret: ${OKTA_CLIENT_SECRET}
        authorization_url: "https://your-domain.okta.com/oauth2/v1/authorize"
        token_url: "https://your-domain.okta.com/oauth2/v1/token"
        user_info_url: "https://your-domain.okta.com/oauth2/v1/userinfo"
        scopes: ["openid", "profile", "email"]
      
      - name: "azure_ad"
        client_id: ${AZURE_CLIENT_ID}
        client_secret: ${AZURE_CLIENT_SECRET}
        tenant_id: ${AZURE_TENANT_ID}
        scopes: ["User.Read"]
  
  # API Key Authentication
  api_keys:
    enabled: true
    header_name: "X-API-Key"
    rate_limit:
      requests_per_minute: 60
      requests_per_hour: 1000

# Authorization (RBAC)
authorization:
  # Roles
  roles:
    - name: "admin"
      permissions:
        - "*"  # All permissions
    
    - name: "power_user"
      permissions:
        - "documents:read"
        - "documents:write"
        - "documents:delete"
        - "search:*"
        - "chat:*"
        - "analytics:read"
    
    - name: "user"
      permissions:
        - "documents:read"
        - "documents:write:own"
        - "search:execute"
        - "chat:create"
    
    - name: "viewer"
      permissions:
        - "documents:read"
        - "search:execute"
  
  # Permission definitions
  permissions:
    documents:
      - "read"
      - "write"
      - "delete"
      - "admin"
    
    search:
      - "execute"
      - "advanced"
      - "export"
    
    chat:
      - "create"
      - "history"
      - "delete"
    
    analytics:
      - "read"
      - "write"
    
    system:
      - "config"
      - "users"
      - "audit"

# Encryption
encryption:
  # Data at rest
  at_rest:
    enabled: true
    algorithm: "AES-256-GCM"
    key_rotation_days: 90
    
    # Field-level encryption
    field_encryption:
      enabled: true
      fields:
        - "documents.content"
        - "user.email"
        - "api_keys.key"
  
  # Data in transit
  in_transit:
    tls_version: "1.3"
    cipher_suites:
      - "TLS_AES_256_GCM_SHA384"
      - "TLS_CHACHA20_POLY1305_SHA256"
      - "TLS_AES_128_GCM_SHA256"
    
    certificate:
      path: "/secrets/tls.crt"
      key_path: "/secrets/tls.key"
      ca_path: "/secrets/ca.crt"

# Access Control
access_control:
  # IP Whitelisting
  ip_whitelist:
    enabled: false
    allowed_ips:
      - "10.0.0.0/8"
      - "172.16.0.0/12"
      - "192.168.0.0/16"
  
  # Rate Limiting
  rate_limiting:
    enabled: true
    default:
      requests_per_minute: 60
      requests_per_hour: 1000
      requests_per_day: 10000
    
    by_endpoint:
      "/api/v1/search":
        requests_per_minute: 30
      "/api/v1/generate":
        requests_per_minute: 10
      "/api/v1/documents/upload":
        requests_per_minute: 5
  
  # CORS
  cors:
    enabled: true
    allowed_origins:
      - "https://app.yourcompany.com"
      - "https://staging.yourcompany.com"
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["*"]
    allow_credentials: true
    max_age_seconds: 3600

# Audit Logging
audit:
  enabled: true
  
  # Events to log
  events:
    - "authentication.success"
    - "authentication.failure"
    - "authorization.denied"
    - "document.upload"
    - "document.delete"
    - "search.execute"
    - "data.export"
    - "config.change"
    - "user.create"
    - "user.delete"
  
  # Storage
  storage:
    type: "elasticsearch"  # or "postgres", "s3"
    retention_days: 365
    
    elasticsearch:
      host: "localhost:9200"
      index_prefix: "rag-audit-"
      
  # Privacy
  privacy:
    anonymize_queries: true
    exclude_content: true
    hash_user_ids: true

# Security Headers
security_headers:
  X-Frame-Options: "DENY"
  X-Content-Type-Options: "nosniff"
  X-XSS-Protection: "1; mode=block"
  Strict-Transport-Security: "max-age=31536000; includeSubDomains"
  Content-Security-Policy: "default-src 'self'; script-src 'self' 'unsafe-inline';"
  Referrer-Policy: "strict-origin-when-cross-origin"

# Secrets Management
secrets:
  provider: "vault"  # or "aws_secrets_manager", "azure_key_vault"
  
  vault:
    address: "https://vault.yourcompany.com"
    namespace: "rag-system"
    auth_method: "kubernetes"  # or "token", "approle"
    role: "rag-service"
    
    paths:
      api_keys: "secret/data/rag/api-keys"
      encryption_keys: "secret/data/rag/encryption"
      certificates: "secret/data/rag/certificates"